### ISSUE TITLE
Visibility params don't work on players disguised as players

### ISSUE THREAD

**Issue by Frogperson** [robingrether/iDisguise#5] opened 2017-04-20 14:35 UTC
So yeah as stated in the title, the command `/disguise sheep red visibility=not-list visibility-param=MyAltAccount` works just fine; my alt can still see me as me, and other see me as a red sheep. But when I switch "sheep red" to "player SomePlayer" ` /disguise player SomePlayer visibility=not-list visibility-param=MyAltAccount` then everybody, including my alt see me as SomePlayer.

**Comment by luisagrether** [comment] 2017-04-21 09:27
It is true that executing `/disguise player SomePlayer visibility=not-list visibility-param=MyAltAccount` does not affect the visibility of the player disguise. But this is not a bug. The problem is just that iDisguise does not parse any additional arguments after the player name. So in order to get this to work, you have to execute two commands: first disguise yourself using `/disguise player SomePlayer` then afterwards adjust the visibility using only `/disguise visibility=not-list visibility-param=MyAltAccount`

**Comment by Frogperson** [comment] 2017-04-21 16:49
Awesome, thanks for the clarification! Just tested it and it works perfectly. 

I have another small question so I guess I'll just ask it here.
We're trying to use this plugin for a UHC where everyone is disguised as one player and teaming is allowed. The problem is, we would like it so teams can have their names colored so that it's not quite as confusing during a fight. Using the built-in Minecraft teams for this didn't work (as I was kind of expecting). I'm unsure of how "deep" the disguises are, but do you think that another plugin could possibly solve this?

Oh after looking at it a bit more it looks like I may be able to use the custom-name param? Is it possible to do this while disguised as a player? Doing the command `/disguise custom-name=&6SomePlayer` gives me  this error`Wrong usage: unknown arguments custom-name=&6SomePlayer`

**Comment by luisagrether** [comment] 2017-04-21 20:25
You can't apply custom names to a player disguise. But player disguises support coloring and formatting. Just try it: `/disguise player &cNotch`

Additionally, via the API you can set both display name and skin name of a player disguise completely independent from each other. This might be the thing you're looking for. If you wish, I could add a command for this feature as well.

**Comment by Frogperson** [comment] 2017-04-21 21:30
I think I can make it work with just the `/disguise player &cNotch`, but if you could add the command to have skin and name separate like that, that would be awesome.

**Comment by Frogperson** [comment] 2017-04-23 02:28
Okay so I think I have almost everything working how I'd like, but after some more testing it seems I've run into a couple more problems.

First problem:
In the config file, no matter what I have `modify-message-death` and `modify-message-kill` set to, the kills and deaths are always showing the disguised name instead of the actual player.

Second problem:
Even though I have `modify-player-list-entry` set to false, it still seems to be modifying it slightly. Here's what I mean
 
My view (correct)
![image](https://cloud.githubusercontent.com/assets/17440180/25309834/6c22d1d0-27a5-11e7-873d-d45a371e5067.png)

Other people's view (incorrect)
![image](https://cloud.githubusercontent.com/assets/17440180/25309848/95965564-27a5-11e7-9245-c67f4c829e06.png)

As you can see, other people can correctly see the undisguised username, but it's stripped of the color and the hearts. Is this something that would be fixed if you add the commands for separate skin and names? Or is it just a different problem altogether?

**Comment by luisagrether** [comment] 2017-04-23 09:40
I've already received another report about the first problem you mentioned a few days ago. It will be fixed in the next release, until then you may use the latest snapshot file which you can grab over here: https://www.robingrether.de/idisguise/

The second problem has nothing to do with that player disguise skin name stuff. I've known this problem for a while now, but I could not find a proper solution for it. However, I will keep trying out new things as soon as possible.

**Comment by Frogperson** [comment] 2017-04-23 18:51
Dude, you've been so awesome so far! Hopefully you'll be able to work out a solution to that second problem soon. We'd really like to have hearts and team colors in tab for our UHC this weekend. Please let me know if there's anything I can do to help.

**Comment by luisagrether** [comment] 2017-04-23 20:45
I'm afraid I have to disappoint you: I won't have time to do any coding until next weekend since I'm having my A-level exams this week and they're very important to me.

**Comment by Frogperson** [comment] 2017-04-24 01:56
No worries, we'll work something out. Good luck on your exams!

**Comment by luisagrether** [comment] 2017-05-02 15:04
When you have time, maybe you could test the latest snapshot of iDisguise which you can [grab here](https://www.robingrether.de/idisguise/).

In this version you can use either _/disguise player &lt;name&gt;_ like it was before (color and format codes are supported) or _/disguise player &lt;skin&gt; &lt;name&gt;_ to set skin and display name independent from each other.

**Comment by Frogperson** [comment] 2017-05-05 17:57
Hey sorry it took so me so long to respond, Just tested those commands and and they seem to work perfectly. That will definitely make things a bit easier if we do another UHC like this.

**Comment by luisagrether** [comment] 2017-06-08 15:49
I think I figured out a way to fix the player list problem. Which plugin did you use to append that health bar to the player names? I'd appreciate if I could use that plugin to test my code.

**Comment by luisagrether** [comment] 2017-07-01 10:43
Scoreboard and team problems should be finally fixed in 5.6.4-SNAPSHOT #6 which you can grab over here: https://www.robingrether.de/idisguise/

**Comment by Frogperson** [comment] 2017-07-02 00:04
Oh awesome thanks for updating it! Sorry for not getting back to you on the plugin by the way. Had to ask someone which one we used again and then I completely forgot to send you the link. If you would still like it I'm pretty sure this is the UHC plugin we used which did the hearts in the tab menu. https://www.spigotmc.org/resources/ultrahardcore-reloaded.1622/

**Closed as completed** 2017-08-19 13:24 UTC
Labels: bug, help wanted

**Comment by luisagrether** [comment] 2017-08-19 13:27
Finally, you may switch to the official release (5.6.4) which contains the fix as well.

https://www.spigotmc.org/resources/idisguise.5509/
