### ISSUE TITLE
Scoreboard bug with snapshot 

### ISSUE THREAD

**Issue by T1MOXA** [robingrether/iDisguise#11] opened 2017-06-25 02:10 UTC
![image](https://user-images.githubusercontent.com/19938629/27513170-7ec2c570-5964-11e7-9ce6-da3d3f112a7e.png)
https://github.com/RienBijl/Scoreboard

**Comment by luisagrether** [comment] 2017-06-28 09:14
Well, I don't know what that picture should tell me. But I assume this is a duplicate of the bug you mentioned in the other issue...

**Closed as completed by luisagrether** 2017-06-28 09:14 UTC
Labels: duplicate
