### ISSUE TITLE
Disguising as player does not work for servers in offline mode (inc BungeeCord)

### ISSUE THREAD

**Issue by eob2000** [robingrether/iDisguise#15] opened 2017-10-28 19:12 UTC
I am running a 3 server network through bungeecord, that requires me to set each individual server to offline mode. This has the sideeffect of making iDisguise not work for players, the name changes but the skin either remains unchanged or becomes the default steve.

Can this be fixed please, Thank you:

All the individual servers are running Spigot 1.12

**Comment by luisagrether** [comment] 2017-11-01 13:32
This problem is not related to offline servers. Disguising as players works just fine if you do it on a normal offline server.

The problem is BungeeCord. It rewrites player skins in order to maintain a global player list. However, I haven't found a way to fix this problem (prevent BC from rewriting skins), thus I can't help you for now.

**Comment by luisagrether** [comment] 2017-12-26 14:20
After a HUGE amount of time, I've finally found a fix for this issue :D 

You may download iDisguise 5.7.1-SNAPSHOT `#`13 over here: https://www.robingrether.de/idisguise/

(You have to enable _disguise.bungee-cord_ in the _config.yml_ to make the fix take effect)

**Comment by luisagrether** [comment] 2018-05-12 22:54
Finally, iDisguise 5.7.1 is officially released. Therefore I close this thread...

**Closed as completed by luisagrether** 2018-05-12 22:54 UTC
Labels: bug
